export { default as ImagenOpcional } from "./ImagenOpcional/ImagenOpcional";
export { default as BaseInfo } from "./BaseInfo/BaseInfo";
export { default as HitPoints } from "./HitPoints/HitPoints";
export { default as Atributos } from "./Atributos/Atributos";
export { default as Inspo } from "./Inspo/Inspo";
export { default as TirarDados } from "./TirarDados/TirarDados";
export { default as Habilidades } from "./Habilidades/Habilidades";
export { default as Menu } from "./Menu/Menu";
export { default as FormEditar } from "./FormEditar/FormEditar";
